### ISSUE TITLE
Addon reports error voidling not found on bar

### ISSUE THREAD

**Issue by markdall** [kaminaris/MaxDps-Priest#2]
The addon reports error voidling not found on bar. When I googled it, voidling is a mind bender glyph. Not every priest will have it.

Noticed in MaxDPS-Priest 9.0.1.

**Comment by GeorgeFlorian** [comment]
Until this gets fixed, use this: https://easyupload.io/vtyl4h

**Comment by avleen** [comment]
Pull request submitted :)
